#!/bin/sh

if grep -q "ipq" "/etc/openwrt_release"; then
	if grep -q "ipq40xx" "/etc/openwrt_release"; then
		sys_temp = "$(sensors | grep -Eo '\+[0-9]' | sed ':a;N;$!ba;s/\n/ /g;s/+//g')" || sys_temp=0
	else
		sys_temp = "$(awk '{ printf("%.0f", $0 / 1000) }' /sys/class/thermal/thermal_zone0/temp)" || sys_temp=0
	fi
	echo -n "${sys_temp}"
else
	if grep -q "bcm27xx" "/etc/openwrt_release"; then
		cpu_temp="$(vcgencmd measure_temp | awk -F '=' '{print $2}' | awk -F "'" '{print $1}')" || cpu_temp=0 
	else
		cpu_temp="$(awk "BEGIN{printf (\"%.0f\n\",$(cat /sys/class/thermal/thermal_zone0/temp)/1000) }")" || cpu_temp=0
	fi
	echo -n "${cpu_temp}"
fi
