#!/bin/sh

THERMAL_PATH="/sys/class/thermal/thermal_zone0/temp"

if grep -q "x86" "/etc/openwrt_release"; then
	# Intel
	cpu_temp="$(sensors "coretemp-*" 2>"/dev/null" | grep -E "(Core )" | grep -Eo "\+[0-9]*" | head -n1 | tr -d "+")"
	# AMD
	[ -n "${cpu_temp}" ] || cpu_temp="$(sensors "k*temp-*" 2>"/dev/null" | awk '/Tdie/ {print $2}' | head -n1 | tr -d "+")"
else
	[ ! -e "$THERMAL_PATH" ] || \
		cpu_temp="$(awk '{printf("%.f, $0 / 1000)}' "$THERMAL_PATH")"
fi
echo -n "${cpu_temp}"

